FROM debian:buster

MAINTAINER Adam Cecile <acecile@le-vert.net>

ENV TERM xterm
ENV HOSTNAME @@HOSTNAME@@
ENV SMTP_SERVER @@SMTP_SERVER@@
ENV SMTP_MAIL_ALIAS root@@@HOSTNAME@@

ENV CENTREON_MAJOR 20.04
ENV CENTREON_VERSION 20.04.19
ENV CENTREON_GORGONE_VERSION 20.04.11
ENV CENTREON_WIDGET_GRAPH_MONITORING_VERSION 20.04.1
ENV CENTREON_WIDGET_SERVICE_MONITORING_VERSION 20.04.4
ENV CENTREON_WIDGET_HOST_MONITORING_VERSION 20.04.5
ENV CENTREON_WIDGET_SERVICEGROUP_MONITORING_VERSION 20.04.0
ENV CENTREON_WIDGET_HOSTGROUP_MONITORING_VERSION 20.04.0
ENV CENTREON_WIDGET_LIVE_TOP10_CPU_USAGE_VERSION 20.04.0
ENV CENTREON_WIDGET_LIVE_TOP10_MEMORY_USAGE_VERSION 20.04.0
ENV CENTREON_WIDGET_ENGINE_STATUS_VERSION 20.04.1
ENV CENTREON_WIDGET_GRID_MAP_VERSION 20.04.0
ENV CENTREON_WIDGET_HTTPLOADER_VERSION 20.04.0
ENV CENTREON_WIDGET_TACTICAL_OVERVIEW_VERSION 20.04.0
ENV CENTREON_WIDGET_GLOBAL_HEALTH 20.04.0

ENV VMWARE_PERL_SDK @@VMWARE_PERL_SDK@@


### Update Debian system
RUN echo "deb http://deb.debian.org/debian/ buster main contrib non-free" > /etc/apt/sources.list \
    && echo "deb http://security.debian.org/ buster/updates main contrib non-free" >> /etc/apt/sources.list
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' dist-upgrade


### Install base system
RUN DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install \
    supervisor \
    nullmailer bsd-mailx \
    cron \
    rsyslog \
    rrdtool \
    less \
    sudo \
    rsync \
    nagios-plugins nagios-plugins-contrib nagios-nrpe-plugin \
    apache2 php-fpm \
    snmp snmp-mibs-downloader \
    libmonitoring-plugin-perl \
    xinetd \
    vim nano \
    gnupg
# Fix check_icmp not being setuid root
RUN dpkg-statoverride --update --add root root 4755 /usr/lib/nagios/plugins/check_icmp
RUN dpkg-statoverride --update --add root root 4755 /usr/lib/nagios/plugins/check_dhcp
# Enable default MIBs
RUN sed -i 's!^\(mibs\s:\)$!#\1!' /etc/snmp/snmp.conf
# Configure nullmailer
RUN mkfifo /var/spool/nullmailer/trigger \
    && chown mail:root /var/spool/nullmailer/trigger \
    && chmod 0622 /var/spool/nullmailer/trigger \
    && echo "${HOSTNAME}" > /etc/mailname \
    && echo "${SMTP_SERVER}" > /etc/nullmailer/remotes \
    && echo "${SMTP_MAIL_ALIAS}" > /etc/nullmailer/adminaddr
# Set Apache to UTC timezone
RUN sed -i 's!^;\?\(date\.timezone[[:space:]]*=[[:space:]]*\).*$!\1 UTC!' /etc/php/7.3/fpm/php.ini

#### Install centreon engine and related
# ln -s /usr/lib/nagios/plugins/centreon_plugins.pl: Workaround meta services not working
# mklive-status for nagvis or thruk installation
# Rename files that will be exported as external volumes and dpkg-divert initscript, replaced by a script calling supervisorctl
ADD https://packages.le-vert.net/packages.le-vert.net.gpg.key /tmp/
RUN echo 'deb [trusted=yes] http://packages.le-vert.net/monitoring/debian/ buster main' >> /etc/apt/sources.list \
      && apt-key add /tmp/packages.le-vert.net.gpg.key \
      && echo 'Package: centreon-broker centreon-engine centreon-connector centreon-plugins libcentreon-clib' > /etc/apt/preferences.d/centreon.pref \
      && echo "Pin: version $CENTREON_MAJOR.*" >> /etc/apt/preferences.d/centreon.pref \
      && echo 'Pin-Priority: 1000' >> /etc/apt/preferences.d/centreon.pref \
      && cat /etc/apt/preferences.d/centreon.pref \
      && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' dist-upgrade \
      && DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install \
         centreon-broker centreon-engine centreon-connector centreon-plugins libdate-manip-perl \
      && ln -s /usr/lib/nagios/plugins/centreon_plugins.pl /usr/lib/nagios/plugins/centreon_centreon_central.pl \
      && DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install \
         check-mk-livestatus \
      && mv /etc/centreon-broker /etc/centreon-broker.initial \
      && mv /etc/centreon-engine /etc/centreon-engine.initial \
      && mv /var/lib/centreon-engine /var/lib/centreon-engine.initial \
      && mv /var/log/centreon-engine /var/log/centreon-engine.initial \
      && mv /var/lib/centreon-broker /var/lib/centreon-broker.initial \
      && mv /var/log/centreon-broker /var/log/centreon-broker.initial \
      && dpkg-divert --add --rename /etc/init.d/centengine \
      && dpkg-divert --add --rename /etc/init.d/centcore \
      && dpkg-divert --add --rename /etc/init.d/cbd
COPY files/etc/init.d/centengine /etc/init.d/
COPY files/etc/init.d/cbd /etc/init.d/
RUN chmod 0755 /etc/init.d/centengine /etc/init.d/cbd


### Cassandra monitoring require cassandra binaries and JRE
RUN echo 'deb [trusted=yes] http://www.apache.org/dist/cassandra/debian 311x main' >> /etc/apt/sources.list
ADD https://www.apache.org/dist/cassandra/KEYS /tmp/
RUN apt-key add /tmp/KEYS
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install \
    cassandra openjdk-8-jre-headless


### Install centreon gorgone
# After build-essential (included) is required to build ZMQ::LibZMQ4 which is not available as Debian package
# Dep libdbd-sqlite3-perl is not shown but happens when you start gorgoned with a valid config file
RUN DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install \
    perl-modules \
    libjson-xs-perl \
    libcryptx-perl \
    libcrypt-cbc-perl \
    libyaml-perl \
    libdbi-perl \
    libyaml-libyaml-perl \
    libhash-merge-perl \
    libdbd-sqlite3-perl \
    build-essential \
    cpanminus \
    libzmq3-dev \
    libtest-tcp-perl \
    libtest-fatal-perl \
    libtest-requires-perl \
    libtry-tiny-perl \
    libdevel-checklib-perl \
    libtask-weaken-perl \
    && cpanm --notest ZMQ::LibZMQ4
WORKDIR /tmp
ADD	https://github.com/centreon/centreon-gorgone/archive/refs/tags/$CENTREON_GORGONE_VERSION.tar.gz /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION.tar.gz
RUN     mkdir centreon-gorgone-$CENTREON_GORGONE_VERSION && tar xzf centreon-gorgone-$CENTREON_GORGONE_VERSION.tar.gz -C centreon-gorgone-$CENTREON_GORGONE_VERSION --strip-components=1
WORKDIR /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION
RUN     echo 'GORGONE_LOG="/var/log/centreon-gorgone"' > /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION/unattended-response \
          && echo 'GORGONE_VARLIB="/var/lib/centreon-gorgone"' >> /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION/unattended-response \
          && echo 'GORGONE_VARLIB="/var/lib/centreon-gorgone"' >> /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION/unattended-response \
          && echo 'GORGONE_ETC="/etc/centreon-gorgone"' >> /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION/unattended-response \
          && echo 'GORGONE_BINDIR="/usr/bin/"' >> /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION/unattended-response \
          && echo 'GORGONE_PERL=`eval "\`perl -V:installvendorlib\`"; echo $installvendorlib`' >> /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION/unattended-response \
          && echo 'SYSCONFIG="/etc/default"' >> /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION/unattended-response \
          && echo 'GORGONE_USER="centreon-gorgone"' >> /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION/unattended-response \
          && echo 'GORGONE_GROUP="centreon-gorgone"' >> /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION/unattended-response \
          && /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION/install.sh  -f /tmp/centreon-gorgone-$CENTREON_GORGONE_VERSION/unattended-response
COPY files/etc/init.d/gorgoned /etc/init.d/
RUN  mv /etc/centreon-gorgone /etc/centreon-gorgone.initial \
     && mv /var/lib/centreon-gorgone /var/lib/centreon-gorgone.initial \
     && mv /var/log/centreon-gorgone /var/log/centreon-gorgone.initial \
     && chmod 0755 /etc/init.d/gorgoned

### Install centreon Web
RUN DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install \
    php php-mysql php-ldap php-gd php-sqlite3 php-intl \
    php-pear php-auth-sasl php-mdb2 php-date php-net-smtp php-net-socket php-validate php-xmlrpc php-soap \
    librrds-perl libdbi-perl libdbd-mysql-perl libnet-snmp-perl libconfig-inifiles-perl \
    php-mbstring
# Not available in Debian Buster
# php-db
WORKDIR /tmp
# DO NOT USE GITHUB URL HERE
# IT LOOKS BEING THE SAME BUT IT'S NOT
# MISS ALL check_* scripts
ADD	https://s3-eu-west-1.amazonaws.com/centreon-download/public/centreon/centreon-web-$CENTREON_VERSION.tar.gz /tmp/
RUN     mkdir centreon-web-$CENTREON_VERSION && tar xzf centreon-web-$CENTREON_VERSION.tar.gz -C centreon-web-$CENTREON_VERSION --strip-components=1 \
          && sed -i 's!/usr/lib64/centreon-connector!/usr/lib/centreon-connector!g' /tmp/centreon-web-$CENTREON_VERSION/libinstall/CentWeb.sh  \
          && sed -i 's!/usr/lib64/centreon-connector!/usr/lib/centreon-connector!g' /tmp/centreon-web-$CENTREON_VERSION/www/install/var/engines/centreon-engine \
          && sed -i 's!/usr/lib64/centreon-engine!/usr/lib/centreon-engine!g' /tmp/centreon-web-$CENTREON_VERSION/www/install/var/engines/centreon-engine \
          && sed -i 's!/usr/lib64/nagios/cbmod.so!/usr/lib/centreon-broker/cbmod.so!g' /tmp/centreon-web-$CENTREON_VERSION/www/install/var/brokers/centreon-broker \
          && sed -i 's!/usr/share/centreon/lib/centreon-broker!/usr/lib/centreon-broker/modules!g' /tmp/centreon-web-$CENTREON_VERSION/www/install/var/brokers/centreon-broker \
          && sed -i 's!/usr/share/centreon-engine!/usr!g' /tmp/centreon-web-$CENTREON_VERSION/www/install/var/engines/centreon-engine
WORKDIR /tmp/centreon-web-$CENTREON_VERSION
RUN     cat tmpl/vardistrib/debian-8 >> tmpl/vardistrib/local \
          && echo CENTREON_ENGINE_CONNECTORS=/usr/lib/centreon-connector >> tmpl/vardistrib/local \
          && echo CENTREON_PLUGINS=/usr/lib/nagios/plugins >> tmpl/vardistrib/local \
          && echo INSTALL_DIR_CENTREON=/srv/centreon >> tmpl/vardistrib/local \
          && echo DIR_PHP_FPM_CONF=/etc/php/7.3/fpm/pool.d >> tmpl/vardistrib/local \
          && echo GORGONE_VARLIB=/var/lib/centreon-gorgone >> tmpl/vardistrib/local \
          && echo GORGONE_CONFIG=/etc/centreon-gorgone >> tmpl/vardistrib/local \
          && echo GORGONE_USER=centreon-gorgone >> tmpl/vardistrib/local \
          && echo GORGONE_GROUP=centreon-gorgone >> tmpl/vardistrib/local \
          && sed -i 's!yes_no_default "$(gettext "Is the Gorgone module already installed?")"!true!' ./install.sh \
          && groupadd centreon && useradd -g centreon centreon \
          && mv /bin/hostname /bin/hostname.orig && /bin/echo -e "/bin/sh\n\necho ${HOSTNAME}" > /bin/hostname && chmod 755 /bin/hostname \
          && /bin/bash ./install.sh -f tmpl/vardistrib/local \
          && mkdir -p /etc/centreon/config.d && chown www-data:centreon /etc/centreon/config.d && chmod 0755 /etc/centreon/config.d \
          && mv /bin/hostname.orig /bin/hostname \
          && a2enconf centreon \
          && a2enmod proxy_fcgi \
          && a2enmod rewrite \
          && a2enmod headers
# Reinstall check_centreon_dummy that has been dropped
COPY files/usr/lib/nagios/plugins/check_centreon_dummy /usr/lib/nagios/plugins/
RUN chmod 0755 /usr/lib/nagios/plugins/check_centreon_dummy
# Workaround centreon-partitioning.php *script* (there is also a cron with same filename)
# not being installed by install.sh
RUN	cp -v bin/centreon-partitioning.php /usr/share/centreon/bin/ \
          && chmod 0755 /usr/share/centreon/bin/centreon-partitioning.php \
          && sed -i "s|realpath(dirname(__FILE__) . '/../config/centreon.config.php')|'/srv/centreon/config/centreon.config.php'|" /usr/share/centreon/bin/centreon-partitioning.php \
          && mkdir -p `perl -e 'for (@INC) { print $_."\n" and exit() if ($_ =~ /^\/usr\/local\/share\/perl/) }'` \
          && cp -a /tmp/centreon-web-$CENTREON_VERSION/lib/perl/centreon `perl -e 'for (@INC) { print $_."\n" and exit() if ($_ =~ /^\/usr\/local\/share\/perl/) }'` \
          && mv /etc/centreon /etc/centreon.initial \
          && mv /var/lib/centreon /var/lib/centreon.initial

### Setup supervisor to start all processes
COPY files/root/start.sh /root/
COPY files/etc/supervisor/conf.d/apache2.conf /etc/supervisor/conf.d/
COPY files/etc/supervisor/conf.d/php-fpm.conf /etc/supervisor/conf.d/
COPY files/etc/supervisor/conf.d/cron.conf /etc/supervisor/conf.d/
COPY files/etc/supervisor/conf.d/rsyslogd.conf /etc/supervisor/conf.d/
COPY files/etc/supervisor/conf.d/nullmailer.conf /etc/supervisor/conf.d/
COPY files/etc/supervisor/conf.d/centengine.conf /etc/supervisor/conf.d/
COPY files/etc/supervisor/conf.d/cbd.conf /etc/supervisor/conf.d/
COPY files/etc/supervisor/conf.d/gorgoned.conf /etc/supervisor/conf.d/
COPY files/etc/supervisor/conf.d/xinetd.conf /etc/supervisor/conf.d/
COPY files/etc/xinetd.d/mklive /etc/xinetd.d/


### DELL EqualLogic monitoring
COPY files/git-repositories/check_equallogic/check_equallogic.sh /usr/lib/nagios/plugins/
RUN chmod 755 /usr/lib/nagios/plugins/check_equallogic.sh


### IPMI monitoring
COPY files/git-repositories/check_ipmi_simple/check_ipmi_simple_chassis.py /usr/lib/nagios/plugins/
COPY files/git-repositories/check_ipmi_simple/check_ipmi_simple_sensors.py /usr/lib/nagios/plugins/
RUN chmod 755 /usr/lib/nagios/plugins/check_ipmi_simple_chassis.py \
      && chmod 755 /usr/lib/nagios/plugins/check_ipmi_simple_sensors.py \
      && DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install \
         freeipmi-tools

### RabbitMQ monitoring
COPY files/git-repositories/nagios-plugins-rabbitmq/scripts/check_rabbitmq_aliveness /usr/lib/nagios/plugins/
COPY files/git-repositories/nagios-plugins-rabbitmq/scripts/check_rabbitmq_exchange /usr/lib/nagios/plugins/
COPY files/git-repositories/nagios-plugins-rabbitmq/scripts/check_rabbitmq_partition /usr/lib/nagios/plugins/
COPY files/git-repositories/nagios-plugins-rabbitmq/scripts/check_rabbitmq_shovels /usr/lib/nagios/plugins/
COPY files/git-repositories/nagios-plugins-rabbitmq/scripts/check_rabbitmq_cluster /usr/lib/nagios/plugins/
COPY files/git-repositories/nagios-plugins-rabbitmq/scripts/check_rabbitmq_objects /usr/lib/nagios/plugins/
COPY files/git-repositories/nagios-plugins-rabbitmq/scripts/check_rabbitmq_queue /usr/lib/nagios/plugins/
COPY files/git-repositories/nagios-plugins-rabbitmq/scripts/check_rabbitmq_watermark /usr/lib/nagios/plugins/
COPY files/git-repositories/nagios-plugins-rabbitmq/scripts/check_rabbitmq_connections /usr/lib/nagios/plugins/
COPY files/git-repositories/nagios-plugins-rabbitmq/scripts/check_rabbitmq_overview /usr/lib/nagios/plugins/
COPY files/git-repositories/nagios-plugins-rabbitmq/scripts/check_rabbitmq_server /usr/lib/nagios/plugins/
RUN chmod 755 /usr/lib/nagios/plugins/check_rabbitmq_aliveness \
     && chmod 755 /usr/lib/nagios/plugins/check_rabbitmq_exchange \
     && chmod 755 /usr/lib/nagios/plugins/check_rabbitmq_partition \
     && chmod 755 /usr/lib/nagios/plugins/check_rabbitmq_shovels \
     && chmod 755 /usr/lib/nagios/plugins/check_rabbitmq_cluster \
     && chmod 755 /usr/lib/nagios/plugins/check_rabbitmq_objects \
     && chmod 755 /usr/lib/nagios/plugins/check_rabbitmq_queue \
     && chmod 755 /usr/lib/nagios/plugins/check_rabbitmq_watermark \
     && chmod 755 /usr/lib/nagios/plugins/check_rabbitmq_connections \
     && chmod 755 /usr/lib/nagios/plugins/check_rabbitmq_overview \
     && chmod 755 /usr/lib/nagios/plugins/check_rabbitmq_server


### DNS monitoring
RUN DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install \
    dnsutils

### Add VMware/ESX monitoring
RUN apt-get update \
      && DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install \
        libssl-dev \
        perl-doc \
        libxml-libxml-perl \
        libxml2-dev \
        uuid-dev \
        kmod \
        expect \
        libdevel-stacktrace-perl libclass-data-inheritable-perl libconvert-asn1-perl libcrypt-openssl-rsa-perl libcrypt-x509-perl libexception-class-perl libpath-class-perl libtry-tiny-perl libnet-inet6glue-perl libuuid-random-perl \
        libcrypt-ssleay-perl \
        libarchive-zip-perl libclass-methodmaker-perl libdata-dump-perl libsoap-lite-perl libuuid-perl \
        libwww-perl libnet-http-perl libsocket6-perl \
        libmodule-build-perl
COPY files/other/vmware/$VMWARE_PERL_SDK /tmp/
COPY files/other/vmware/auto_install_vmware_sdk.sh /tmp/
COPY files/other/vmware/vmware_sdk_Possible_precedence_issue_with_control_flow_operator.patch /tmp/
# Install it
WORKDIR /tmp
# Workaround old SDK not working properly on recent PERL.... (dead slow)
# Sleep to avoid text file busy bug when running ./auto_install_vmware_sdk.sh
RUN tar xvzf "$VMWARE_PERL_SDK" \
      && if `echo "$VMWARE_PERL_SDK" | grep -qE '(SDK-6.0|SDK-5.5)'`; then \
        apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install make wget \
          && wget https://github.com/libwww-perl/libwww-perl/archive/libwww-perl/5.837.tar.gz \
          && tar xzf 5.837.tar.gz \
          && cd libwww-perl-libwww-perl-5.837/ \
          && perl Makefile.PL INSTALL_BASE=/opt/libwww-perl-5.837 \
          && make \
          && make install \
          && sed -i '1 i\use lib "/opt/libwww-perl-5.837/lib/perl5";' /tmp/vmware-vsphere-cli-distrib/lib/VMware/share/VMware/VICommon.pm \
          && patch /tmp/vmware-vsphere-cli-distrib/lib/VMware/share/VMware/VICommon.pm < /tmp/vmware_sdk_Possible_precedence_issue_with_control_flow_operator.patch; \
      fi \
    && cd /tmp \
    && echo ubuntu > /etc/tmp-release \
    && chmod 0755 auto_install_vmware_sdk.sh \
    && sleep 1 \
    && ./auto_install_vmware_sdk.sh
# check_vmware_esx script
RUN DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install \
    libtime-duration-perl
COPY files/git-repositories/check_vmware_esx/check_vmware_esx.pl /usr/lib/nagios/plugins/
COPY files/git-repositories/check_vmware_esx/modules /usr/lib/nagios/vmware/modules/
# In order to get the script working, need to change the path
RUN sed -i 's!^#\(use lib "/usr/lib/nagios/vmware/modules";\)!\1!' /usr/lib/nagios/plugins/check_vmware_esx.pl
# Otherwise the script crash when ran from /root
RUN chmod 0755 /root
# End VMware/ESX monitoring

# Start BigData monitoring
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install \
    nagios-plugins-harisekhon
RUN sed -i 's!/state\.json!/state!' /usr/lib/nagios/plugins/check_mesos_master_state.pl
RUN sed -i 's!/state\.json!/state!' /usr/lib/nagios/plugins/check_mesos_slave_state.pl
# End BigData monitoring

### check_json
COPY files/git-repositories/check_json/check_json.pl /usr/lib/nagios/plugins/
RUN chmod 755 /usr/lib/nagios/plugins/check_json.pl
RUN sed -i 's!Nagios::Plugin!Monitoring::Plugin!g' /usr/lib/nagios/plugins/check_json.pl
RUN DEBIAN_FRONTEND=noninteractive apt-get -y -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' --no-install-recommends --no-install-suggests install \
    libwww-perl libjson-perl libmonitoring-plugin-perl

# Centreon Widgets
# No working download link for graph-monitoring
ADD https://github.com/centreon/centreon-widget-graph-monitoring/archive/$CENTREON_WIDGET_GRAPH_MONITORING_VERSION.tar.gz /tmp/centreon-widget-graph-monitoring-$CENTREON_WIDGET_GRAPH_MONITORING_VERSION.tar.gz
ADD https://github.com/centreon/centreon-widget-service-monitoring/archive/$CENTREON_WIDGET_SERVICE_MONITORING_VERSION.tar.gz /tmp/centreon-widget-service-monitoring-$CENTREON_WIDGET_SERVICE_MONITORING_VERSION.tar.gz
ADD https://github.com/centreon/centreon-widget-host-monitoring/archive/$CENTREON_WIDGET_HOST_MONITORING_VERSION.tar.gz /tmp/centreon-widget-host-monitoring-$CENTREON_WIDGET_HOST_MONITORING_VERSION.tar.gz
ADD https://github.com/centreon/centreon-widget-servicegroup-monitoring/archive/$CENTREON_WIDGET_SERVICEGROUP_MONITORING_VERSION.tar.gz /tmp/centreon-widget-servicegroup-monitoring-$CENTREON_WIDGET_SERVICEGROUP_MONITORING_VERSION.tar.gz
ADD https://github.com/centreon/centreon-widget-hostgroup-monitoring/archive/$CENTREON_WIDGET_HOSTGROUP_MONITORING_VERSION.tar.gz /tmp/centreon-widget-hostgroup-monitoring-$CENTREON_WIDGET_HOSTGROUP_MONITORING_VERSION.tar.gz
ADD https://github.com/centreon/centreon-widget-live-top10-cpu-usage/archive/$CENTREON_WIDGET_LIVE_TOP10_CPU_USAGE_VERSION.tar.gz /tmp/centreon-widget-live-top10-cpu-usage-$CENTREON_WIDGET_LIVE_TOP10_CPU_USAGE_VERSION.tar.gz
ADD https://github.com/centreon/centreon-widget-live-top10-memory-usage/archive/$CENTREON_WIDGET_LIVE_TOP10_MEMORY_USAGE_VERSION.tar.gz /tmp/centreon-widget-live-top10-memory-usage-$CENTREON_WIDGET_LIVE_TOP10_MEMORY_USAGE_VERSION.tar.gz
ADD https://github.com/centreon/centreon-widget-engine-status/archive/$CENTREON_WIDGET_ENGINE_STATUS_VERSION.tar.gz /tmp/centreon-widget-engine-status-$CENTREON_WIDGET_ENGINE_STATUS_VERSION.tar.gz
ADD https://github.com/centreon/centreon-widget-grid-map/archive/$CENTREON_WIDGET_GRID_MAP_VERSION.tar.gz /tmp/centreon-widget-grid-map-$CENTREON_WIDGET_GRID_MAP_VERSION.tar.gz
ADD https://github.com/centreon/centreon-widget-httploader/archive/$CENTREON_WIDGET_HTTPLOADER_VERSION.tar.gz /tmp/centreon-widget-httploader-$CENTREON_WIDGET_HTTPLOADER_VERSION.tar.gz
ADD https://github.com/centreon/centreon-widget-tactical-overview/archive/$CENTREON_WIDGET_TACTICAL_OVERVIEW_VERSION.tar.gz /tmp/centreon-widget-tactical-overview-$CENTREON_WIDGET_TACTICAL_OVERVIEW_VERSION.tar.gz
ADD https://github.com/centreon/centreon-widget-global-health/archive/$CENTREON_WIDGET_GLOBAL_HEALTH.tar.gz /tmp/centreon-widget-global-health-$CENTREON_WIDGET_GLOBAL_HEALTH.tar.gz
RUN tar xvf /tmp/centreon-widget-graph-monitoring-$CENTREON_WIDGET_GRAPH_MONITORING_VERSION.tar.gz --strip-components=1 -C /srv/centreon/www/widgets/ && rm /tmp/centreon-widget-graph-monitoring-$CENTREON_WIDGET_GRAPH_MONITORING_VERSION.tar.gz
RUN tar xvf /tmp/centreon-widget-service-monitoring-$CENTREON_WIDGET_SERVICE_MONITORING_VERSION.tar.gz --strip-components=1 -C /srv/centreon/www/widgets/ && rm /tmp/centreon-widget-service-monitoring-$CENTREON_WIDGET_SERVICE_MONITORING_VERSION.tar.gz
RUN tar xvf /tmp/centreon-widget-host-monitoring-$CENTREON_WIDGET_HOST_MONITORING_VERSION.tar.gz --strip-components=1 -C /srv/centreon/www/widgets/ && rm /tmp/centreon-widget-host-monitoring-$CENTREON_WIDGET_HOST_MONITORING_VERSION.tar.gz
RUN tar xvf /tmp/centreon-widget-servicegroup-monitoring-$CENTREON_WIDGET_SERVICEGROUP_MONITORING_VERSION.tar.gz --strip-components=1 -C /srv/centreon/www/widgets/ && rm /tmp/centreon-widget-servicegroup-monitoring-$CENTREON_WIDGET_SERVICEGROUP_MONITORING_VERSION.tar.gz
RUN tar xvf /tmp/centreon-widget-hostgroup-monitoring-$CENTREON_WIDGET_HOSTGROUP_MONITORING_VERSION.tar.gz --strip-components=1 -C /srv/centreon/www/widgets/ && rm /tmp/centreon-widget-hostgroup-monitoring-$CENTREON_WIDGET_HOSTGROUP_MONITORING_VERSION.tar.gz
RUN tar xvf /tmp/centreon-widget-live-top10-cpu-usage-$CENTREON_WIDGET_LIVE_TOP10_CPU_USAGE_VERSION.tar.gz --strip-components=1 -C /srv/centreon/www/widgets/ && rm /tmp/centreon-widget-live-top10-cpu-usage-$CENTREON_WIDGET_LIVE_TOP10_CPU_USAGE_VERSION.tar.gz
RUN tar xvf /tmp/centreon-widget-live-top10-memory-usage-$CENTREON_WIDGET_LIVE_TOP10_MEMORY_USAGE_VERSION.tar.gz --strip-components=1 -C /srv/centreon/www/widgets/ && rm /tmp/centreon-widget-live-top10-memory-usage-$CENTREON_WIDGET_LIVE_TOP10_MEMORY_USAGE_VERSION.tar.gz
RUN tar xvf /tmp/centreon-widget-engine-status-$CENTREON_WIDGET_ENGINE_STATUS_VERSION.tar.gz --strip-components=1 -C /srv/centreon/www/widgets/ && rm /tmp/centreon-widget-engine-status-$CENTREON_WIDGET_ENGINE_STATUS_VERSION.tar.gz
RUN tar xvf /tmp/centreon-widget-grid-map-$CENTREON_WIDGET_GRID_MAP_VERSION.tar.gz --strip-components=1 -C /srv/centreon/www/widgets/ && rm /tmp/centreon-widget-grid-map-$CENTREON_WIDGET_GRID_MAP_VERSION.tar.gz
RUN tar xvf /tmp/centreon-widget-httploader-$CENTREON_WIDGET_HTTPLOADER_VERSION.tar.gz --strip-components=1 -C /srv/centreon/www/widgets/ && rm /tmp/centreon-widget-httploader-$CENTREON_WIDGET_HTTPLOADER_VERSION.tar.gz
RUN tar xvf /tmp/centreon-widget-tactical-overview-$CENTREON_WIDGET_TACTICAL_OVERVIEW_VERSION.tar.gz --strip-components=1 -C /srv/centreon/www/widgets/ && rm /tmp/centreon-widget-tactical-overview-$CENTREON_WIDGET_TACTICAL_OVERVIEW_VERSION.tar.gz
RUN tar xvf /tmp/centreon-widget-global-health-$CENTREON_WIDGET_GLOBAL_HEALTH.tar.gz --strip-components=1 -C /srv/centreon/www/widgets/ && rm /tmp/centreon-widget-global-health-$CENTREON_WIDGET_GLOBAL_HEALTH.tar.gz

EXPOSE 80 6557

@@DOCKERFILELOCAL@@

RUN rm -rf /tmp/*
WORKDIR /root


ENTRYPOINT ["/bin/bash", "/root/start.sh"]
